version: '3.5'
services:
  fb-scraper:
    build: .
    # command: /code/keepAlive.bash
    # command: python3.7 /code/seleniumHeadlessModThreadsSuperList.py -n 365 -p 16
    # command: sleep 100000000
    command: bash -c "/code/oneYearEuro.bash"
    volumes:
       - .:/code
    ports:
       - 3000:3000
    stdin_open: true
    tty: true
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    image: postgres:11
    ports:
     - 5432:5432
    volumes:
       - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
