version: '3.7'
services:
  chrome:
    build: .
    #command: python /code/manage.py runserver 0.0.0.0:8000
    # volumes:
    #   - .:/code
    #ports:
    #  - 8000:8000
    #depends_on:
    #  - db
    stdin_open: true
    tty: true
  # db:
    # image: postgres:11
    # volumes:
      # - postgres_data:/var/lib/postgresql/data/

# volumes:
  # postgres_data: