version: '3.7'
services:
  fb-scraper:
    build: .
    command: /code/keepAlive.bash
    # command: sleep 100000000
    volumes:
       - .:/code
    stdin_open: true
    tty: true
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    image: postgres:11
    ports:
     - 5432
    volumes:
       - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: